# Generated by Django 3.1.3 on 2021-06-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wrong_order', models.IntegerField(default=0)),
                ('file_pass', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('meta_call', models.IntegerField(default=0)),
                ('meta_ttl', models.IntegerField(default=0)),
                ('meta_vol', models.IntegerField(default=0)),
                ('pull_stat', models.IntegerField(default=0)),
                ('pull_loc', models.IntegerField(default=0)),
                ('pull_supp', models.IntegerField(default=0)),
                ('pull_hsup', models.IntegerField(default=0)),
                ('pull_due', models.IntegerField(default=0)),
                ('pull_mult', models.IntegerField(default=0)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inventory.library')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barCode', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('call_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('inorder', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_books', to='inventory.file')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='inventory.library')),
            ],
        ),
    ]
