# Generated by Django 3.1.3 on 2021-06-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='Untitled 06/13/21', max_length=100),
        ),
    ]
