# Generated by Django 3.2.4 on 2021-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_file_not_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='Untitled-06/16/21', max_length=100),
        ),
    ]
