# Generated by Django 3.2.4 on 2021-06-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210616_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='Untitled-06/17/21', max_length=100),
        ),
    ]
