# Generated by Django 3.2.4 on 2021-06-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='Untitled-06/20/21', max_length=100),
        ),
    ]
