# Generated by Django 3.2.4 on 2021-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='Untitled-06/22/21', max_length=100),
        ),
    ]
